### ISSUE TITLE
TA Information

### ISSUE THREAD

**Issue by Sotaur** [Sotaur/CS202-Website#2]
Stub things out, adding dummy content probably of us. Take a look at the [CS 340 website](https://students.cs.byu.edu/~cs340ta/winter2019/TA/) for ideas.

**Comment by Sotaur** [comment]
@jerodw What do you think should belong on this page? Would the TAs for this class have office hours? Or would this page just have bio information and which section each TA is responsible for?

**Comment by RyanRemer** [comment]
I created a page that resembles the CS 240 site, with better style
